---
- name: Install Clickhouse
  hosts: clickhouse
  remote_user: admin
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector
  remote_user: admin
  roles:
    - vector-role

- name: Install lighthouse
  hosts: lighthouse
  remote_user: admin
  handlers:
    - name: Start nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: restarted
  pre_tasks:
    - name: add repo
      become: true
      ansible.builtin.copy:
        dest: /etc/yum.repos.d/nginx.repo
        content: |
          [nginx-stable]
          name=nginx stable repo
          baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
          gpgcheck=1
          enabled=1
          gpgkey=https://nginx.org/keys/nginx_signing.key
          module_hotfixes=true
    - name: Install nginx
      become: true
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Create nginx config
      become: true
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /etc/nginx/conf.d/default
        mode: "0644"
      notify: Start nginx service
  roles:
    - lighthouse-role
