- name: Check nginx present
  become: true
  ansible.builtin.package:
    name: nginx
    state: present

- name: Check git present
  become: true
  ansible.builtin.package:
    name: git
    state: present

- name: Reload nginx service
  systemd:
    name: nginx
    state: restarted
