---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 31.44.3.62
    jenkins-agent-01:
      ansible_host: 188.227.85.192
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: root